-- =============================================================================
-- Diagram Name: news_portal
-- Created on: 12/19/2025 7:31:46 PM
-- Diagram Version:
-- =============================================================================

-- +goose Up
-- +goose StatementBegin

CREATE TABLE "statuses" (
	"statusId" int4 NOT NULL,
	PRIMARY KEY("statusId")
);

CREATE TABLE "categories" (
	"categoryId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"orderNumber" int4 NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("categoryId")
);

CREATE TABLE "tags" (
	"tagId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(100) NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("tagId")
);

CREATE TABLE "news" (
	"newsId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"categoryId" int4 NOT NULL,
	"title" varchar(255) NOT NULL,
	"content" text,
	"author" varchar(50) NOT NULL,
	"publishedAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"tagIds" int4[] NOT NULL DEFAULT '{}',
	"statusId" int4 NOT NULL,
	PRIMARY KEY("newsId")
);

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_categories" FOREIGN KEY ("categoryId")
	REFERENCES "categories"("categoryId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "categories" ADD CONSTRAINT "Ref_categories_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "tags" ADD CONSTRAINT "Ref_tags_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS "news";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "tags";
DROP TABLE IF EXISTS "statuses";

-- +goose StatementEnd

