// Code generated by colgen v0.1.2; DO NOT EDIT.
package rest

import (
	"github.com/daniilsolovey/news-portal/internal/newsportal"
)

type Categories []Category

func NewCategories(in []newsportal.Category) Categories { return Map(in, NewCategory) }

func (ll Categories) IndexByCategoryID() map[int]Category {
	r := make(map[int]Category, len(ll))
	for i := range ll {
		r[ll[i].CategoryID] = ll[i]
	}
	return r
}

type NewsList []News

func NewNewsList(in []newsportal.News) NewsList { return Map(in, NewNews) }

func (ll NewsList) IndexByNewsID() map[int]News {
	r := make(map[int]News, len(ll))
	for i := range ll {
		r[ll[i].NewsID] = ll[i]
	}
	return r
}

type Tags []Tag

func NewTags(in []newsportal.Tag) Tags { return Map(in, NewTag) }

func (ll Tags) IndexByTagID() map[int]Tag {
	r := make(map[int]Tag, len(ll))
	for i := range ll {
		r[ll[i].TagID] = ll[i]
	}
	return r
}
