// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"log/slog"

	"github.com/daniilsolovey/news-portal/internal/db"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func Initialize() (*Service, func(), error) {
	logger := ProvideLogger()
	repository, cleanup, err := ProvideDB(logger)
	if err != nil {
		return nil, nil, err
	}
	manager := ProvideNewsPortal(repository, logger)
	newsHandler := ProvideHandler(manager, logger)
	echo := ProvideEngine(newsHandler)
	service := &Service{
		Postgres: repository,
		Logger:   logger,
		Engine:   echo,
	}
	return service, func() {
		cleanup()
	}, nil
}

// wire.go:

type Service struct {
	Postgres *db.Repository
	Logger   *slog.Logger
	Engine   *echo.Echo
}
