// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/daniilsolovey/news-portal/internal/repository/postgres"
	"github.com/gin-gonic/gin"
	"log/slog"
)

// Injectors from wire.go:

func Initialize() (*Service, func(), error) {
	logger := ProvideLogger()
	repository, cleanup, err := ProvidePostgres(logger)
	if err != nil {
		return nil, nil, err
	}
	iRepository := ProvideRepository(repository)
	templateUseCase := ProvideUseCase(iRepository, logger)
	templateHandler := ProvideHandler(templateUseCase, logger)
	engine := ProvideEngine(templateHandler)
	service := &Service{
		Postgres: repository,
		Logger:   logger,
		Engine:   engine,
	}
	return service, func() {
		cleanup()
	}, nil
}

// wire.go:

type Service struct {
	Postgres *postgres.Repository
	Logger   *slog.Logger
	Engine   *gin.Engine
}
